version: 2
jobs:
  build:
    docker:
      - image: epitechcontent/epitest-docker

    steps:
      - checkout

      - run:
          name: Build
          command: make re
      - run:
          name: Checking artifact
          command: ls client
      - run:
          name: Testing build project
          command: sudo ./client -t localhost -p 4242 -P epitech
