version: 2
jobs:
  build:
    docker:
      - image: gcc

    steps:
      - checkout

      - run:
          name: Build
          command: make re
      - run:
          name: Checking artifact
          command: ls client
      - run:
          name: Executing artifact
          command: sudo ./client -t localhost -p 1337 -P epitech
